### ISSUE TITLE
@VictorKong94  Victor, my LaTeX meet some troubles

### ISSUE THREAD

**Issue by karenceli** [berkeley-stat159/project-delta#100]
@VictorKong94  Victor, my LaTeX meet some troubles. Could you please check the report.tex(which is the draft report) and transform it into a pdf version?

**Comment by VictorKong94** [comment]
What exactly do you want me to do?

**Comment by karenceli** [comment]
I don't know whether we need a pdf version of the draft report( some groups have pdf while others don't). But I have some troubles with git ... So could you please make a pdf version of the draft report? I've already finished the discussion of result part. Thank you!

**Comment by VictorKong94** [comment]
I got the pdf up but I'm not really sure how to solve your git problem. I know this one guy in zeta just deletes and remakes his fork every time something weird happens, but I'm pretty sure that's not the way we're supposed to do it. You might want to ask Ross or something?

**Comment by karenceli** [comment]
Ok! Thank you for your advice! I just don't know whether we should pull the pdf version of the draft report here... If necessary, could you please pull the pdf version? Thank you so much!

**Comment by karenceli** [comment]
Oh, do we need to delete the previous pdf report?I notice that in other groups there only exists the report.tex

**Comment by VictorKong94** [comment]
I'm not sure about that, but I guess we can just keep it up just in case. It's the most recent version after considering your additions, so it shouldn't hurt.
