### ISSUE TITLE
IMPORTANT

### ISSUE THREAD

**Issue by VictorKong94** [berkeley-stat159/project-delta#126]
Heads up, everybody. Going to change the name of the `run()` class to `ds005()` because `run()` is already a python built-in.

**Comment by liuanna** [comment]
OK. Would you mind also adding images of BOLD files in the class? I need nii files for some plots.

**Comment by yfxia** [comment]
Okay. I'll also edit the original smooth method in the class, I just now see the correct way to calculate sigma for Gaussian filter.

**Comment by VictorKong94** [comment]
Wait, @liuanna. What do you mean by that? Isn't the BOLD data already there?

**Comment by liuanna** [comment]
I would like to have both image (which is just ```self.img = nib.load(path_BOLD)```) and data.

**Comment by VictorKong94** [comment]
I can do that, but what else do you need from `img = nib.load(path_BOLD)`?

**Comment by liuanna** [comment]
Since I am generating some fancy plots using [nilearn package] (http://nilearn.github.io/auto_examples/index.html), some functions require an image object.

**Comment by VictorKong94** [comment]
Alright, I'll get on it. Are you working on those plots now?

**Comment by liuanna** [comment]
Thanks. I am working on these plots right now.

**Comment by VictorKong94** [comment]
Okay, I'll upload this ASAP and just add documentation and tests later then. The name will probably not be self.img, but I'll give you the details in a bit.

**Comment by VictorKong94** [comment]
Okay, I've uploaded something that worked on my computer. Sorry for the wait; it turned out to be more complicated than I thought.

**Comment by liuanna** [comment]
Thanks. By the way, I think the make_class misses the time_course function.

**Comment by VictorKong94** [comment]
Oops. Just saw this. I'll change it to img().
