### ISSUE TITLE
Explanation for late submission

### ISSUE THREAD

**Issue by liuanna** [berkeley-stat159/project-delta#151]
@jarrodmillman Sorry to bother you now. Our group encountered a weird issue in the last minute. Some of our text submissions were just gone, and we took a while to figure this out and submitted our final report late. Sorry about that. We understand this is not an excuse, but we just wish you know that we worked very hard on this project and really got depressed by this accident. Sorry again.

**Comment by jarrodmillman** [comment]
No problem.  Thanks for letting me know.
