### ISSUE TITLE
make dataset doesn't work

### ISSUE THREAD

**Issue by rossbar** [berkeley-stat159/project-delta#152]
When I run make dataset, I get the following error:

```
tar -xvzf data/ds005_mnifunc.tar -C data/

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make: *** [dataset] Error 2
```
Please push the fix as soon as possible

**Comment by liuanna** [comment]
Thanks for letting us know. I think all of our team members are very busy about finals at this moment, and I also have one tomorrow. We will try to fix it by tomorrow night.

**Comment by liuanna** [comment]
@rossbar We revised the Makefile, and it works on our computers. Hope it will be fine now.

**Comment by rossbar** [comment]
`make dataset` now works on my system, but I immediately ran into issues again with make validate-data.

Please verify that your entire process runs with a fresh install. Clone your project into a new directory and run the commands you specify in the order that you specify. When you have verified that your process chain will run error-free and have pushed the changes, notify me

**Comment by yfxia** [comment]
@rossbar We have verified the entire process runs with a fresh install. It's all clear now. Thank you very much for your help and patience. We are sorry about the delay of submission.

**Comment by rossbar** [comment]
Thanks for taking a look! :+1:
