### ISSUE TITLE
sklearn package for regression and machine learning

### ISSUE THREAD

**Issue by liuanna** [berkeley-stat159/project-delta#58]
We are able to use sklearn package to perform logistic regression, svm, randomForest, and many other machine learning tools. With this handy tool, we don't need to write functions for these models but we do need write scripts to run them. So please download  (```pip install -U scikit-learn```) and explore the package a little bit.

**Comment by karenceli** [comment]
http://peekaboo-vision.blogspot.de/2013/01/machine-learning-cheat-sheet-for-scikit.html Here is a link that I think might be helpful to get to know about for scikit learn~
