### ISSUE TITLE
Objects

### ISSUE THREAD

**Issue by VictorKong94** [berkeley-stat159/project-delta#65]
Do you guys think it'd be worthwhile to write a class to organize the fMRI data and the behavioral data by combinations of subject and run number? I have a part of a prototype that I've been on and off with but I don't know if it'd be useful enough to keep pursuing. Tell me what you think?

**Comment by yfxia** [comment]
1. What do you mean by 'class'? Do you mean the mechanism in C++?
2. If we understand it correctly, for each subject, we will have 6 files, so in total it will be 96 files, right?

**Comment by VictorKong94** [comment]
They won't create new files. Only sort the data in the Python session. Meaning the BOLD data and the behavioral data for subject 1 run 1 will be attributed to one object, the BOLD data and the behavioral data for subject 1 run 2 will be attributed to a second object, and so on. We could the attach methods that do the analysis as well.
