### ISSUE TITLE
OH with Jarrod

### ISSUE THREAD

**Issue by liuanna** [berkeley-stat159/project-delta#66]
Hi Jarrod @jarrodmillman:
We plan to have a group meeting with you next week. What date and time are you available on next Wednesday and Thursday? Please let us know. Thanks.

**Comment by jarrodmillman** [comment]
I have time between 9:30-10:30 and 14-16 on Wednesday (11/25).  I won't be on campus on Thursday, but could meet anytime on Friday (11/27).

**Comment by liuanna** [comment]
Thanks for letting us know your schedule. Could we make an appointment on Friday from 1pm to 3pm? Thank you.

**Comment by jarrodmillman** [comment]
OK.  Although, hopefully it won't take 2 hours.  See you at 13:00 on Friday (11/27).

**Comment by jarrodmillman** [comment]
Barker Hall is locked today, so I will meet you in front of the building at the main entrance (the side facing LKS) at 13:00 today.  See you soon.

**Comment by liuanna** [comment]
Thanks for letting us know and see you soon!
