### ISSUE TITLE
Problem with utils_function::construct_mat

### ISSUE THREAD

**Issue by VictorKong94** [berkeley-stat159/project-delta#73]
After checking around a bit, it doesn't look like the "euclidean distance" computed here isn't what it sounds to be. First issue, column 4 (which is actually the fifth column) is taking the "unbinaried" repsonses of the subjects. I think you may have meant column 3 (the actual fourth column), but I'm still not quite sure how those values were computed. If this is the case, you may need to reconsider you analysis from \texttt{run_logistic_model.py}.

I am adding a \texttt{design_matrix} method to the class I created, using what I think is what you meant to do. Let me know what your thoughts are.

**Comment by liuanna** [comment]
First of all, we have no clue on the column 3 (the actual fourth column) PTval, so we will not use it at all. I indeed used the column 4 which is respnum. respnum somehow represents how confident when a participant decides whether gamble or not. According to the supplemental paper on page 3 which you can find in the reference folder, we calculate the "Euclidean distance of the gain/loss combination from the diagonal of the gamble matrix". My understanding of the gamble matrix should look like this:

|   | gamble | not gamble |
| ------------- |:-------------:| -----:|
| strong      | # of 1 | # of 4 |
| weak     | # of 2     |   # of 3 |

**Comment by yfxia** [comment]
I'm currently modifying run_logistic_model.py for the logistic regression, it has not finalized yet, so it might not be ready for test files.

**Comment by liuanna** [comment]
I don't think we need to add test file for scripts, but only functions. In addition, @VictorKong94 you do not need to write test functions for logistic_model.py in model, since we will use sklearn package for logistic regression. You can directly delete the file logistic_model.py in code/model.

**Comment by VictorKong94** [comment]
My mistake! I see it now! I'm going to add it into the class as a method now, if that's okay.

**Comment by liuanna** [comment]
That's ok. But please do not delete the construct_mat function in utils_function.py at this moment since all previous scripts are using this function. I will modify previous scripts and start using this method after you finish this part. Thanks.

**Comment by VictorKong94** [comment]
Can you actually link me the source that contains this formula?

**Comment by VictorKong94** [comment]
I feel like these would be the euclidean distances from the diagonal of the gamble matrix:
<img width="764" alt="euclid" src="https://cloud.githubusercontent.com/assets/12565675/11323261/1921de06-90c3-11e5-9e59-adfa1733be9b.png">

**Comment by liuanna** [comment]
I feel like this makes more sense. Would you mind showing the formula and code?

**Comment by yfxia** [comment]
The matrix looks neat. We were having long conservation trying to understand the what are euclidean distances in the context.

**Comment by VictorKong94** [comment]
Yeah, I think it's super confusing because they only put the graphic in the published article and then only put the explanation in the supplement so you had to look at both to understand what they did. Below is a picture of the matrix they had in the published article:
![20151122_121500_hdr](https://cloud.githubusercontent.com/assets/12565675/11326038/2a038922-9113-11e5-9e28-af0fe3cddabf.jpg)
I haven't written the code yet, but I'm going to work on it now. I'll let you know when I have it and send it to you.

**Comment by VictorKong94** [comment]
I just made a merge request. The code that calculates \texttt{euclidean distance}, along with documentation, is under the .design_matrix() method in make_class.py. I'm going to get back to work on writing tests now but let me know if you want any more functionality in the \texttt{run} class.

**Comment by liuanna** [comment]
Nice work! I think you have added most of the functions in utils_functions.py as methods. At this moment, I don't have specific functions that I want to add.
