### ISSUE TITLE
Meeting with Jarrod on Friday (11/27)

### ISSUE THREAD

**Issue by liuanna** [berkeley-stat159/project-delta#74]
Dear all, 
We plan to have a group meeting with Jarrod on Friday (11/27). Please comment if you are available on that day and what time will work for you. After the meeting with Jarrod, we will probably have a group meeting. Thanks.

**Comment by karenceli** [comment]
Isn't Friday 11/27? Anyway, thank you so much for your work! I'm available on both Friday and the weekend~

**Comment by liuanna** [comment]
@karenceli Thanks for pointing it out. I corrected the date. Thanks for letting us know your schedule.
