### ISSUE TITLE
ideas about group proj

### ISSUE THREAD

**Issue by karenceli** [berkeley-stat159/project-delta#9]
I think due to the limit of available data, our main topic might still have to be analyzing the neural basis of loss aversion in decision-making under risk, which may be almost the same with other groups. However, can we make some changes about the initial model? For example, the authors assessed behavioral sensitivity to gains and losses by fitting a logistic regression. Can we construct more than one model so that we could use linear discriminate analysis or quadratic discriminate analysis? Through comparison, we could gain a better model. On the other hand, the number of predictors is quite small. So it might not be a quite good idea to use Ridge regression or lasso.

**Comment by yfxia** [comment]
We could possibly start with looking at one participant for one task run or so, just to have a basic idea of what we should do, then think about different subjects. Also, for detailed version of how authors perform statistical analysis, http://www.sciencemag.org/content/suppl/2007/01/22/315.5811.515.DC1/Tom.SOM.pdf
